stages:
  - mavenbuild
  - maventest
maven-build: #this is a JOB
  stage: mavenbuild
  tags:
    - kyle_tag
  script:
    - cd Backend/ms_313-main-Backend-debt_buddies_backend/Backend/debt_buddies_backend/springboot_application # to where you have the pom.xml
    - mvn package
maven-test:
   stage: maventest
   tags:
     - kyle_tag
   script:
     - cd Backend/ms_313-main-Backend-debt_buddies_backend/Backend/debt_buddies_backend/springboot_application
     - mvn test

