stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - Owen_tag      # <-- change to your runner's tag
  script:
    - cd Backend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package

maven-test:             
   stage: maventest
   tags:
     - Owen_tag     # <-- change to your runner's tag
   script:
     - cd Backend       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
     - mvn test
